# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20170826_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u0437\u0430\u0434\u0430\u0447\u0430', 'verbose_name_plural': '\u0417\u0430\u0434\u0430\u0447\u0438'},
        ),
        migrations.AddField(
            model_name='task',
            name='post_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041e\u0442\u0441\u043b\u0435\u0436\u0438\u0432\u0430\u0435\u043c\u044b\u0439 \u043f\u043e\u0441\u0442'),
        ),
    ]
