# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20170826_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='post_id',
            new_name='post_link',
        ),
    ]
